const date = Date.now();
const initialTasks = [
    {
      height: "56",
      id: 'lkj645lkj5464lk456jl456',
      title: 'Example task, click to edit',
      isSwiped: false,
      isCompleted: false,
      isOpen: false,
      dateCreated: date,
      // isOverdue: false,
      // isDueSoon: false,
      // distanceToNow: null,
      // dueDate: null,
      // dateCompleted: null,
    },
    {
      height: "56",
      id: '097gdf08g7d90f8g7df098g7y',
      title: 'Swipe to delete',
      isSwiped: false,
      isCompleted: false,
      isOpen: false,
      dateCreated: date,
      // isOverdue: false,
      // isDueSoon: false,
      // distanceToNow: null,
      // dueDate: null,
      // dateCompleted: null,
    },
    {
      height: "56",
      id: 'kljngfifgnwrt6469fsd5ttsh',
      title: 'Click to open',
      isSwiped: false,
      isCompleted: false,
      isOpen: false,
      dateCreated: date,
      // isOverdue: false,
      // isDueSoon: false,
      // distanceToNow: null,
      // dueDate: null,
      // dateCompleted: null,
    },
    {
      height: "56",
      id: '090f8g7fsdfs645fdf098g7y',
      title: 'Swipe to delete',
      isSwiped: false,
      isCompleted: false,
      isOpen: false,
      dateCreated: date,
      // isOverdue: false,
      // isDueSoon: false,
      // distanceToNow: null,
      // dueDate: null,
      // dateCompleted: null,
    },
    {
      height: "56",
      id: 'kljngfifsdfs546wsd5ttsh',
      title: 'Click the handle on the right to open',
      isSwiped: false,
      isCompleted: false,
      isOpen: false,
      dateCreated: date,
      // isOverdue: false,
      // isDueSoon: false,
      // distanceToNow: null,
      // dueDate: null,
      // dateCompleted: null,
    },
  ];

export default initialTasks;